services:
  shared-notification-service:
    build: .
    container_name: shared-notification-service
    volumes:
      - ./src:/usr/src/app/src
    command: pnpm start:dev
    env_file:
      - .env
    ports:
      - "3200:3200"  # Puerto HTTP
      - "50057:50057"  # Puerto gRPC
    restart: unless-stopped

  shared-notification-db:
    image: mysql:8.0
    container_name: shared-notification-db
    environment:
      MYSQL_DATABASE: shared-notification-db
      MYSQL_ROOT_PASSWORD: 123456
      TZ: America/Lima
    ports:
      - "3351:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped

networks:
  default:
    driver: bridge