services:
  email-service:
    build: .
    container_name: email-service
    volumes:
      - ./src:/usr/src/app/src
    command: pnpm start:dev
    env_file:
      - .env
    ports:
      - "3200:3200"  # Puerto HTTP
      - "50057:50057"  # Puerto gRPC
    restart: unless-stopped

networks:
  default:
    driver: bridge